### PR TITLE
fix parsing error of api error response (#381)

### LINKED ISSUE #381: APIError message fields may be a array
```
{
  "error": {
    "message": [
      "Invalid schema for function 'xxx': In context=(), object schema missing properties"
    ],
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}
```

### PR DESCRIPTION
**Pull request by vvatanabe**
Fix #381

**Context:**
Basically, it is a `string`. However, if the json schema of the `parameters` field is invalid, as shown below, it is likely to be an `array`.

```bash
$ curl https://api.openai.com/v1/chat/completions -u :$OPENAI_API_KEY -H 'Content-Type: application/json' -d '{
  "model": "gpt-3.5-turbo-0613",
  "messages": [
    {"role": "user", "content": "What is the weather like in Boston?"}
  ],
  "functions": [
    {
      "name": "get_current_weather",
      "parameters": {
        "type": "object"
      }
    }
  ]
}'

{
  "error":{
     "message":[
        "Invalid schema for function 'get_current_weather': In context=(), object schema missing properties"
     ],
     "type":"invalid_request_error",
     "param":null,
     "code":null
  }
}
```

### CODE REVIEW

**Comment by vvatanabe** [comment]
@sashabaranov Please check it.

File: api_test.go [hunk 1]
```diff
@@ -217,13 +319,6 @@ func TestAPIErrorUnmarshalJSONInvalidType(t *testing.T) {
 	checks.HasError(t, err, "Type should be a string")
 }
 
-func TestAPIErrorUnmarshalJSONInvalidMessage(t *testing.T) {
-	var apiErr APIError
-	response := `{"code":418,"message":false,"param":"prompt","type":"teapot_error"}`
-	err := json.Unmarshal([]byte(response), &apiErr)
-	checks.HasError(t, err, "Message should be a string")
-}
-
```
Comment (vvatanabe) [inline api_test.go:226]: This test has been moved to the newly added table test.

**Review by sashabaranov — APPROVED** [review]
Thank you!!
